### ISSUE TITLE
Building model on workers costly

### ISSUE THREAD

**Issue by carterk** [maxpumperla/elephas#10]
Do you find that this step takes a long time? Is the model recompiling the Theano functions here? Would there be ways to speed that up (somehow have the precompiled model persist in memory for each task and just send the weights from the master model in with the map)?

`model = model_from_yaml(self.yaml)`

**Comment by maxpumperla** [comment]
Thanks for the comment. Is certainly comes with a cost. Let me break it down for you:

Each elephas model, regardless the mode (i.e. synch or asynch), has the following steps:
1. Serialize model
2. Send Yaml to workers (check your network bandwidth)
3. De-serialize and re-complile (has to be done)
4. Send initial weights from master to workers
5. Train etc.

There's few things I can image could be changed without disrupting how elephas works. Here's a few remarks:
* I authored the serialization module of keras and there's not much we can improve regarding speed.
* 1. to 4. are only done once, so once you're past it, training should run smoothly.
* Time taken for 1. to 3. is proportional to the size of your model. Since you use elephas, I assume your model is quite large. 
* If you use cheap commodity hardware for workers, 3.-5. are slower than on master. This should be outweighed by parallelization. If it doesn't, don't parallelize.
* You have to (de-)serialize models, as there's no "persisting in memory" in distributed mode. If you don't do it yourself, PySpark will do it for you with CloudPickler. Trying this, you will run into annoying run-time errors quickly (e.g. recursion depth exceeded in pickling).
* Regarding "for each task and just send the weights from the master model in with the map", this is exactly what's happening (broadcasting in synch and http request in asynch)
* Try using TensorFlow, as compilation is usually faster than Theano.
 
Hope this helps. I will leave this open for discussion for a while. Maybe we come up with another idea.

**Comment by carterk** [comment]
Great, thanks for the reply. I'm actually not using Elephas, but I'm developing a very similar framework using Lasagne instead of Keras. Looks like the challenges are identical: I'm hoping to exploit the idea that passing around updated weights and loading them into an already compiled model on a worker is less expensive than passing around updated models and recompiling them on workers.

- I've tried broadcasting a model to each executor only once at the very beginning of training. That model gets compiled in the memory of every executor at that time. 
- Then each epoch I broadcast updated weights (like Elephas does) and pass the broadcast variable (pointer) to the weights and the broadcast variable (pointer) to the model (Elephas passes in a serialized model instead of the broadcast variable) to each task during the map.
- Then on the workers I load the weights (broadcasted each epoch) into the model that is already compiled in executor memory (broadcasted only once at the beginning). And I run a training pass on the data. Note: broadcasted variables are supposed to be read-only, but they can be written to, so updating the model is possible.

The issue is that each task within an executor shares the same broadcasted variables, so you can have simultaneous updating of the worker model by multiple tasks (hence Spark's recommendation that broadcasted variables should be read-only). It seems to me that if each Spark executor made copies of broadcasted variables (enough copies to have one for each task) at the time of the broadcast, and each task could address its own copy of the variable, this method would be ideal. In general, this functionality would make sense for broadcasted variables that are cheap to modify, but expensive to deserialize and compile, like the Theano models here. But it doesn't look like Spark supports that use case.

I've tried it, and that method does significantly speed things up because the model doesn't need to be deserialized and compiled each epoch. And depending on the configuration of partitions/workers used it can work without issue. But it's easy to see issues coming up.

PS I'm using the Spark terminology used here: https://spark.apache.org/docs/1.1.0/cluster-overview.html

**Comment by maxpumperla** [comment]
Cool, sounds great. Maybe in your case you should consider using accumulators instead of broadcast vars, or maybe both, for different tasks.

Just to be clear, though: Nowhere do you find multiple (de-)serializations in elephas. Just once in the beginning. In synchronous mode you only map once and get back deltas. (If we would map several times, your claim were right. But then I'd also structure it differently.) The only difference is that you do the broadcasting of models outside of the map by broadcasting.

In asynch mode, the main/recommended usage of elephas, you receive and send streams of updates via http requests constantly, no models touched. We employ read/write locks to avoid the problems with broadcast variables. The map is just there to kick things off, you could as well do it in another way.

**Comment by maxpumperla** [comment]
You may very well be right that the broadcasting could be faster, though. I should give that a try.

**Comment by carterk** [comment]
Ah, k, I think what I'm doing is something closer to running the equivalent of Elephas's synchronous mode but for many epochs. Something like this:

```
model_broadcast_var = broadcast(model)
weights = model.get_weights()
for i in range(epochs):
   weights_broadcast_var = broadcast(weights)
   deltas = rdd.mapPartitions(lambda data: train_synchronously(data, weights_broadcast_var, model_broadcast_var)).collect()
   weights = update_weights(deltas)
   model = model.load_weights(weights)
```

**Comment by maxpumperla** [comment]
Alright. So, as this doesn't seem to directly be an elephas issue, I'm going to close this. I might opt for the multi-epoch synch mode later, but in my view the asynch mode is superior in any case. Thanks again and all the best for your project.
