### ISSUE TITLE
why use of multi-worker to reduce accuracy

### ISSUE THREAD

**Issue by jovigb** [maxpumperla/elephas#135]
hi，max
I have a question.  when i use of multi-worker to training, more workers lower accuracy. and it's falling sharply. 
why is that? how can i solve it?

**Comment by maxpumperla** [comment]
Hi @jovigb,

there's no such thing as perfect scalability. Have a look at this law and related topics: https://en.wikipedia.org/wiki/Amdahl%27s_law. On top of that SGD is already approximating gradients as is, but if you distribute computation you lose some accuracy.

For small datasets, it's expected to see a sizable drop, but you shouldn't use data parallelism in this case probably. It's a trade-off, really. Let's say you have a model that takes 3 days to train a single epoch and you only can afford to run it for 4 days (cost or time reasons). If you employ 8 workers you can squeeze out 8 epochs, instead of 1. Even if there's a slight drop in accuracy over your _hypothetical_ 24-day single machine  8 epoch run, you're still much better off than your 3-day single epoch run without parallelism. See what I mean? You can also use this to quickly iterate over experiments. It sometimes takes a while before you can be sure your model learns at all. If you can cut this exploration phase by a factor of 8, you can move faster - even if at the end you decide to go for single-machine training for production.

I've used this extensively for training Go bots in the past. It can be worth your while. :D

**Comment by jovigb** [comment]
thanks for your help. maybe as you say. Different model performance differently.
