### ISSUE TITLE
'ElephasEstimator' object has no attribute 'setFeaturesCol'.  Could not interpret optimizer identifier

### ISSUE THREAD

**Issue by romario076** [maxpumperla/elephas#165]
import keras
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras import optimizers, regularizers
from keras.optimizers import Adam

# Set up Deep Learning Model / Architecture
model = Sequential()
model.add(Dense(256, input_shape=(input_dim,)))
model.add(Activation('relu'))
model.add(Dropout(rate=0.3))
model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dropout(rate=0.3))
model.add(Dense(1))
model.add(Activation('relu'))
model.compile(loss='mse', optimizer='adam')

# Set and Serialize Optimizer
optimizer_conf = keras.optimizers.Adam()
opt_conf = serialize(optimizer_conf)

# Initialize SparkML Estimator and Get Settings
estimator = ElephasEstimator()
estimator.set_keras_model_config(model.to_yaml())
estimator.set_num_workers(1)
estimator.setFeaturesCol("features")
estimator.setLabelCol('label')
estimator.set_epochs(25) 
estimator.set_batch_size(64)
estimator.set_verbosity(1)
estimator.set_validation_split(0.10)
estimator.set_optimizer_config(opt_conf)
estimator.set_mode("synchronous")
estimator.set_loss("mse")
estimator.set_metrics(['acc'])

AttributeError: 'ElephasEstimator' object has no attribute 'setFeaturesCol'

dl_pipeline = Pipeline(stages=[estimator])
fit_dl_pipeline = dl_pipeline.fit(train_data)

ValueError: Could not interpret optimizer identifier: False

First error about: estimator.setFeaturesCol("features"), estimator.setLabelCol('label').
If remove them , second error, "Could not interpret optimizer identifier". Tried everything possible, nothing helps.
Please, help.

**Comment by cciliber** [comment]
Hi, same problem.

for me the "setFeaturesCol" error is an issue with pyspark version. Downgrading to 2.4.x solved it. 

I am still struggling with the second one though... any insight would be appreciated! : )

**Comment by cciliber** [comment]
I managed to have the system work with my setup by installing keras version 2.2.4

I hope this helps someone else : )

**Comment by danielenricocahall** [comment]
The issue with the second problem should be resolved in the newest release (1.0.0). Regarding the first two problems, that's because the `HasFeaturesCol` and `HasLabelsCol` mixins were changed in Spark 3.0.0 to remove the setter methods. I could implement those methods in the ElephasEstimator and add a deprecation warning. The input and output are defined through the model, so those methods aren't utilized, although that can be confusing (and in future extensions, we may want to use those features). Let me know if you run into any issues or if you have any thoughts!
