### ISSUE TITLE
Data parallelism on one machine

### ISSUE THREAD

**Issue by mthmn20** [maxpumperla/elephas#29]
This library looks awesome! Does it support data parallel training of a model on multiple GPUs on a single machine?

**Comment by zzz2010** [comment]
I also have the same problem. It seems to me elephas only use single GPUs in my 8-GPUs server.  Looking forward to the solution.  BTW, I used Theano as backend.

Thank you

**Comment by maxpumperla** [comment]
Hey @mthmn20 @zzz2010 that's indeed not very straight forward, as it's not the primary use case I had in mind (distributed mode). Keras, by means of either Theano or Tensorflow, doesn't automatically pick up devices. 

To explicitly register multiple GPUs locally, I'd suggest to virtualize, e.g. by using docker, and have each VM access one of the GPUs. I'll see what I can do, maybe I can provide an example for you.

**Comment by zzz2010** [comment]
Hi, @maxpumperla , is it possible to randomly select available gpu for each worker process?

**Comment by mthmn20** [comment]
@maxpumperla I think François Chollet is apparently working on a [fit_distributed](https://github.com/fchollet/keras/pull/3582#issuecomment-243589285) method for Keras, so it's probably not worth your time to flesh that out here. Was just wondering if it's something you already had done; thanks!

**Comment by maxpumperla** [comment]
@mthmn20 thanks for letting me know, very helpful! 👍

**Comment by marcoleewow** [comment]
Hi, any updates on using elephas on multi-GPUs in a single machine? The codes here looks much more elegant than Chollet's[ keras_distributed.py](https://gist.github.com/fchollet/2c9b029f505d94e6b8cd7f8a5e244a4e) as it uses a lot of tf codes and does not use model.fit(). Also, I would like to use the downpour method in elephas instead of merging outputs in chollet's code.
