### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'master_network'

### ISSUE THREAD

**Issue by EvanZ** [maxpumperla/elephas#97]
From the mnist_mlp_spark.py example:

spark_model = SparkModel(model, frequency='epoch', mode='asynchronous')

In the code, however, SparkModel's 2nd argument is `master_network`. What value should be here?

**Comment by maxpumperla** [comment]
Hey @EvanZ, it's great that you're interested in running the examples. I've mentioned a few times now that master and 0.3 diverge - there's really no need to continue pointing that out. jfyi, the missing argument is the spark context, which isn't really needed anymore (since we can extract it from the RDD or data frame). 

Please consider installing elephas from master:

```
pip install git+https://github.com/maxpumperla/elephas.git
```

**Comment by EvanZ** [comment]
Thanks @maxpumperla! I figured this out late yesterday and installed it that way and have better luck since. There are a few other things I've figured out diverge like setting parameters in `ElephasEstimator`. I'll keep plodding along. ;)
